[package]
name = "docktray"
version = "0.1.0"
description = "Lightweight system tray port and process manager"
authors = ["Alexandr Motologa"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0", features = [] }

[dependencies]
tauri = { version = "2.0", features = ["tray-icon"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sysinfo = "0.33"
netstat2 = "0.11"
bollard = "0.18"
futures-util = "0.3"
tokio = { version = "1", features = ["full"] }

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "z"
strip = true
